language: node_js
node_js:
  - '8'

jobs:
  include:
    - stage: Test
      script: yarn lint
    - script: yarn test:ci
    - stage: Storybook Deploy
      provider: pages
      script: yarn build-storybook
      skip_cleanup: true
      name: 'TravisCI Pages Deployment'
      github_token: $GITHUB_TOKEN
      keep_history: true
      local_dir: storybook-static/
      on:
        branch: master
