language: node_js
node_js:
  - '8'

jobs:
  include:
    - stage: Test
      script: yarn lint
    - script: yarn test:ci
    # - stage: Storybook Deploy
    #   script: yarn deploy-storybook

deploy:
  provider: script
  script: yarn test:ci-coverage
  on:
    branch: master
