language: node_js
node_js:
  - '8'

jobs:
  include:
    - stage: Test
    - script: yarn lint
      name: 'Lint'
    - script: yarn test:ci
      name: 'Test with Coverage'
    - stage: Storybook Deploy
      provider: pages
      skip_cleanup: true
      name: 'TravisCI Pages Deployment'
      github_token: $GITHUB_TOKEN
      keep_history: true
      local_dir: storybook-static/
      on:
        branch: master
